homeassistant:
  customize:
    package.node_anchors:
        entità del purificatore:    &fan    fan.purificatore_soggiorno
        sensor.airq_soggiorno:      &airq   sensor.airq_soggiorno
      # group.famiglia


# Sostituire le entità seguenti:

# - sensor.airq_soggiorno (sensore qualità dell'aria) nel template sensor: Purificatore Aria soggiorno
# - fan.purificatore_soggiorno (entità del purificatore) nel template sensor: Purificatore Aria soggiorno Step

# Se cambiare le nomenclature ricordatevi di cambiare anche nella card


##############################################################################
##                  INPUT_BOOLEAN
################################################
input_boolean:
  purificatore_soggiorno_auto:
    name: Purificatore soggiorno Auto
    icon: mdi:progress-clock
  purificatore_soggiorno_auto_off:
    name: Purificatore soggiorno auto off
    icon: mdi:fan-off
  purificatore_soggiorno_modo_notte:
    name: Purificatore soggiorno modalità notte
    icon: mdi:weather-night
  purificatore_soggiorno_icona_auto:
    name: Purificatore soggiorno icona

##############################################################################
##                  INPUT_BOOLEAN
################################################
input_datetime:
  purificatore_soggiorno_auto_on:
    name: Purificatore soggiorno Auto on
    has_date: false
    has_time: true
  purificatore_soggiorno_auto_off:
    name: Purificatore soggiorno Auto off
    has_date: false
    has_time: true

  purificatore_soggiorno_notte_on:
    name: Purificatore soggiorno notte on
    has_date: false
    has_time: true
  purificatore_soggiorno_notte_off:
    name: Purificatore soggiorno notte off
    has_date: false
    has_time: true

##############################################################################
##                  INPUT_BOOLEAN
################################################
counter:
  purificatore_soggiorno:
    initial: 1
    step: 1
    restore: true
    maximum: 4
    minimum: 1

template:
################################################################################
##                  Sensor
################################################
  - sensor:


      - name: Purificatore Aria soggiorno Step
        unique_id: purificatore_aria_soggiorno_step
        state: >-
          {{ state_attr('fan.purificatore_soggiorno', 'percentage_step')|int |default(33)  }}

################################################################################
##                  Script
###################################################
script:
  purificatore_aria_soggiorno_off:
    alias: "Purificatore Aria soggiorno OFF"
    variables: 
      fan: *fan
    sequence:
      - service: fan.turn_off
        target:
          entity_id: "{{fan}}"
      - service: switch.turn_off
        target:
          entity_id: switch.purificatore_soggiorno_display
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.purificatore_soggiorno_icona_auto

  purificatore_aria_soggiorno:
    alias: "Purificatore Aria soggiorno"
    variables: 
      value: 1
    sequence:
      - service: number.set_value
        data:
          value: '{{value}}'
        target:
          entity_id: number.purificatore_soggiorno_fan_speed_level
      - service: switch.turn_off
        target:
          entity_id: switch.purificatore_soggiorno_display
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.purificatore_soggiorno_icona_auto

  incremento_couter_purifictore_soggiorno:
    alias: "Incremento counter Purificatore soggiorno"
    mode: parallel
    variables: 
      fan: *fan
    sequence:
      - if:
          
              - condition: state
                entity_id: "{{fan}}"
                state: 'on'
        then:
              - service: counter.increment
                target:
                  entity_id: counter.{{ purificatore }}
        else:
              - service: counter.reset
                target:
                  entity_id: counter.{{ purificatore }}
              - service: fan.turn_on
                target:
                  entity_id: "{{fan}}"
              - service: number.set_value
                data:
                  value: 1
                target:
                  entity_id: number.purificatore_soggiorno_fan_speed_level

              - service: switch.turn_off
                target:
                  entity_id: switch.purificatore_soggiorno_display

              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.purificatore_soggiorno_icona_auto

  purificatore_aria_soggiorno_toggle:
    alias: "Purificatore Aria Soggiorno Toggle"
    sequence:
      - service: input_boolean.toggle
        target:
          entity_id:
            - input_boolean.purificatore_soggiorno_modo_notte
            - input_boolean.purificatore_soggiorno_auto_off

################################################################################
##                  Automation
###################################################
automation:
  - alias: "Purificatore Aria soggiorno auto off"
    id: 114d09e50c5b1a26dc286be0d87b6ec2
    initial_state: true
    trigger:
      - platform: time
        at: input_datetime.purificatore_soggiorno_auto_on
      - platform: time
        at: input_datetime.purificatore_soggiorno_auto_off
    action:
      - choose:
          - alias: "OFF"
            conditions:
              - condition: template
                value_template: "{{now().strftime('%H:%M') == states('input_datetime.purificatore_soggiorno_auto_off') [0:5] }}"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.purificatore_soggiorno_auto_off

          - alias: "ON"
            conditions:
              - condition: template
                value_template: "{{now().strftime('%H:%M') == states('input_datetime.purificatore_soggiorno_auto_on') [0:5] }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.purificatore_soggiorno_auto_off

  - alias: "Purificatore Aria soggiorno modo notte"
    id: 8f8f5b69-7046-4f1c-ada1-7a6f9411fcac
    initial_state: true
    trigger:
      - platform: time
        at: input_datetime.purificatore_soggiorno_notte_on
      - platform: time
        at: input_datetime.purificatore_soggiorno_notte_off
    action:
      - choose:
          - alias: "OFF"
            conditions:
              - condition: template
                value_template: "{{now().strftime('%H:%M') == states('input_datetime.purificatore_soggiorno_notte_off') [0:5] }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.purificatore_soggiorno_modo_notte

          - alias: "ON"
            conditions:
              - condition: template
                value_template: "{{now().strftime('%H:%M') == states('input_datetime.purificatore_soggiorno_notte_on') [0:5] }}"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.purificatore_soggiorno_modo_notte

  - alias: "Purificatore Aria soggiorno"
    id: 4287564c4a3f89d6212feb43fa4616c6
    initial_state: true
    mode: restart
    variables:
      airq: *airq
    trigger:

      - id: "piano_m"
        platform: state
        entity_id: counter.purificatore_soggiorno
        to: "1"
        for:
          milliseconds: 500

      - id: "medio_m"
        platform: state
        entity_id: counter.purificatore_soggiorno
        to: "2"
        for:
          milliseconds: 500

      - id: "forte_m"
        platform: state
        entity_id: counter.purificatore_soggiorno
        to: "3"
        for:
          milliseconds: 500

      - id: "spento"
        platform: time
        at: "22:59:00"

      - id: "spento"
        platform: state
        entity_id: group.famiglia
        to: "not_home"

      - id: TEST
        platform: state
        entity_id: *airq


    condition:
      - condition: state
        entity_id: input_boolean.purificatore_soggiorno_auto
        state: "on"
    action:

      - choose:
          - alias: test
            conditions: 
              - "{{trigger.id == 'TEST'}}"
            sequence:
            - choose:
              - conditions: # SPENTO
                  - condition: template
                    value_template: "{{states(airq) |int <= 35}}"
                    for:
                      seconds: 30
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.purificatore_aria_soggiorno_off
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.purificatore_soggiorno_icona_auto

              - conditions: # MEDIO FORTE
                  - condition: time
                    after: input_datetime.purificatore_soggiorno_auto_on
                    before: input_datetime.purificatore_soggiorno_auto_off
                  - condition: state
                    entity_id: group.famiglia
                    state: "home"
                sequence:
                  - choose:
                      - alias: "MEDIO"
                        conditions:
                        - condition: template
                          value_template: "{{states(airq) |int > 35 and states(airq) |int <= 65}}"
                          for:
                            seconds: 10
                        sequence:
                          - service: script.purificatore_aria_soggiorno
                            data: 
                              value: 2
                      - alias: "FORTE" 
                        conditions: # FORTE
                          - condition: template
                            value_template: "{{states(airq) |int > 65}}"
                        sequence:
                          - service: script.purificatore_aria_soggiorno
                            data: 
                              value: 3

          - conditions: # PIANO M
              - alias: "PIANO M"
                condition: trigger
                id: "piano_m"
            sequence:
              - service: script.purificatore_aria_soggiorno
                data: 
                  value: 1


          - conditions: # MEDIO_M
              - alias: "MEDIO M"
                condition: trigger
                id: "medio_m"
            sequence:
              - service: script.purificatore_aria_soggiorno
                data: 
                  value: 2

          - conditions: # SPENTO
              - alias: "SPENTO"
                condition: trigger
                id: "spento"
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.purificatore_aria_soggiorno_off
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.purificatore_soggiorno_icona_auto
          - conditions: # FORTE M
              - alias: "FORTE M"
                condition: trigger
                id: "forte_m"
            sequence:
              - service: script.purificatore_aria_soggiorno
                data: 
                  value: 3

  - alias: "Reset counter Purificatore Soggiorno"
    id: a3eb5331e308efaa93bb6696fca87eb9
    initial_state: true
    trigger:
      - platform: state
        entity_id: counter.purificatore_soggiorno
        to: "4"
    action:
      - service: counter.reset
        target:
          entity_id: counter.purificatore_soggiorno
